authtest/urls.py
#!python
# authtest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
# Add this import
from django.contrib.auth import views
from log.forms import LoginForm

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('log.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}), 
    url(r'^home/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),

    url(r'^survey/', include('multilingual_survey.urls', namespace="survey")),
    url(r'^register/', include('users.urls', namespace="users")), 
    url(r'^graph/', include('fusioncharts.urls', namespace="graph")), 


]

fusioncharts/urls.py
from django.conf.urls import url
from django.contrib import admin
from views import catalogue


from samples import database_example1, database_example2


urlpatterns = [
    url(r'^database-example1/', database_example1.chart, name='chart'),
    url(r'^database-example2/', database_example2.chart, name='chart'),
    
]

log/urls.py
#!python
# log/urls.py
from django.conf.urls import url
from . import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

multilingual_survey/urls.py
from django.conf.urls import url
from multilingual_survey import views


urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', views.survey_form, name='form'),
    url(r'^success/(?P<uuid>\w+)/$', views.survey_success, name='success'),
]

multilingual_survey/models.py
from django.db import models
from django.utils import timezone
from hvad.models import TranslatableModel, TranslatedFields
from django.utils.translation import ugettext_lazy as _
from multilingual_survey.managers import (
    SurveyManager, QuestionManager, ChoiceManager
)


class Survey(TranslatableModel):
    slug = models.SlugField(_('Survey slug'), max_length=200)
    hit = models.PositiveIntegerField(default=0)

    objects = SurveyManager()

    translations = TranslatedFields(
        title=models.CharField(_('Survey title'), max_length=200)
    )

    def __unicode__(self):
        title = self.lazy_translation_getter('title', None)
        if not title:
            title = getattr(self, 'slug', str(self.pk))
        return title

    def admin_title(self):
        return self.__unicode__()

    def questions(self):
        if self.pk:
            return self.question_set.language('').all()
        else:
            return None

    class Meta:
        ordering = ['pk']
        verbose_name = _("Survey")
        verbose_name_plural = _("Surveys")


class Question(TranslatableModel):
    survey = models.ForeignKey(Survey)
    slug = models.SlugField(_('Question slug'), max_length=200)

    objects = QuestionManager()

    translations = TranslatedFields(
        question_text=models.CharField(_('Question text'), max_length=200)
    )

    def __unicode__(self):
        title = self.lazy_translation_getter('question_text', None)
        if not title:
            title = getattr(self, 'slug', str(self.pk))
        return title

    def admin_title(self):
        return self.__unicode__()

    def choices(self):
        if self.pk:
            return self.choice_set.language('').all()
        else:
            return None

    class Meta:
        ordering = ['pk']
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")


class Choice(TranslatableModel):
    question = models.ForeignKey(Question)

    objects = ChoiceManager()

    translations = TranslatedFields(
        choice_text=models.CharField(_('Choice text'), max_length=200)
    )

    def __unicode__(self):
        return self.lazy_translation_getter('choice_text', str(self.pk))

    def admin_title(self):
        return self.__unicode__()

    def get_survey(self):
        return self.question.survey

    class Meta:
        ordering = ['pk']
        verbose_name = _("Choice")
        verbose_name_plural = _("Choices")


class Response(models.Model):
    survey = models.ForeignKey(Survey)
    date_vote = models.DateTimeField(default=timezone.now)
    response_user = models.CharField(
        _('Name of user or identifier'),
        max_length=400
    )
    comments = models.TextField(
        _('Comments'),
        blank=True,
        null=True
    )
    ip = models.GenericIPAddressField()
    response_uuid = models.CharField(
        _("Response unique identifier"),
        max_length=36
    )

    def __unicode__(self):
        return ("response %s" % self.response_uuid)

    class Meta:
        ordering = ['-date_vote']
        verbose_name = _("Response")
        verbose_name_plural = _("Responses")


class Answer(models.Model):
    response = models.ForeignKey(Response)
    choice = models.ForeignKey(Choice)

    class Meta:
        ordering = ['pk']
        verbose_name = _("Answer")
        verbose_name_plural = _("Answers")

multilingual_survey/forms.py
from django import forms
from django.forms import models
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
import uuid
from multilingual_survey.models import Response, Answer, Question, Choice


class HorizontalRadioRenderer(forms.RadioSelect.renderer):
    def render(self):
        return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))


class ResponseForm(models.ModelForm):
    class Meta:
        model = Response
        fields = ('comments',)

    def __init__(self, request=None, *args, **kwargs):
        survey = kwargs.pop('survey')
        self.survey = survey
        super(ResponseForm, self).__init__(*args, **kwargs)
        self.response_uuid = uuid.uuid4().hex

        # Getting IP Address
        if request:
            x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
            if x_forwarded_for:
                ip = x_forwarded_for.split(',')[0]
            else:
                ip = request.META.get('REMOTE_ADDR')
            self.ip = ip

        data = kwargs.get('data')

        for q in self.survey.questions():
            question_choices = q.choices()
            self.fields["question_%d" % q.pk] = forms.ModelChoiceField(
                label=q,
                queryset=question_choices, empty_label=None,
                widget=forms.RadioSelect(renderer=HorizontalRadioRenderer)
            )
            self.fields["question_%d" % q.pk].slug = q.slug
            self.fields["question_%d" % q.pk].required = True
            self.fields["question_%d" % q.pk] \
                .widget.attrs["class"] = "required"

            if data:
                self.fields["question_%d" % q.pk].initial = data.get(
                    'question_%d' % q.pk
                )

    def save(self, commit=True):
        # save the response object
        response = super(ResponseForm, self).save(commit=False)
        response.survey = self.survey
        response.ip = self.ip
        response.response_uuid = self.response_uuid
        response.save()

        # create an answer object for each question and associate it with this
        # response.
        for field_name, field_value in self.cleaned_data.iteritems():
            if field_name.startswith("question_"):
                a = Answer()
                a.choice = field_value
                a.response = response
                a.save()
        return response

multilingual_survey/views.py
from django.shortcuts import get_object_or_404, redirect, render
from multilingual_survey.models import Survey
from multilingual_survey.forms import ResponseForm
from django.contrib.auth.decorators import user_passes_test



def survey_form(request, slug):
    survey = get_object_or_404(Survey, slug=slug)
    form = ResponseForm(request=request, survey=survey)
    if request.method == 'POST':
        form = ResponseForm(data=request.POST, request=request, survey=survey)

        if form.is_valid():
            response = form.save()
            return redirect('survey:success', uuid=response.response_uuid)
        else:
            return render(
                request,
                'multilingual_survey/form.html',
                {'response_form': form, 'survey': survey}
            )
    else:
        return render(
            request,
            'multilingual_survey/form.html',
            {'response_form': form, 'survey': survey}
        )

def survey_success(request, uuid):
    return render(
        request,
        'multilingual_survey/success.html',
        {'uuid': uuid}
    )

multilingual_survey/templates/multilingual_survey/base.html
	{% load staticfiles %}
	<!DOCTYPE html>
	<html>
	<head>

	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	    <title>Auth Demo</title>

	    <!-- Core CSS - Include with every page -->
	    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	</head>

<style >
		body{
     
     background-image: url("https://upload.wikimedia.org/wikipedia/commons/e/e9/Model_Engineering_College_Kochi_Top_view_03.JPG");
	 background-repeat: no-repeat;
	 background-size: cover ;
	}
	</style>
	
   <body>
   
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" >Online Feedback System</a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="/home">home</a></li>
	            <li><a href="">to fill</a></li>
	            <li><a href="#">to fill</a></li>
	            <li class="divider"></li>
	            
	            <li class="divider"></li>
	            <li><a href="/logout">Logout</a></li>
	          </ul>
	        </li>

	      </ul>
	    </div>
	  </div>
	</nav>
	
	
		


	            {% block content %}
	            {% endblock %}

	    <!-- Core Scripts - Include with every page -->
	    <script src = "{% static 'js/jquery.min.js' %}"></script>

	    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
	    {% block javascript %}
	    {% endblock %}

	</body>

	</html>

multilingual_survey/templates/multilingual_survey/form.html
{% extends 'base.html' %}
{% block content %}

{% load url from future %}
{% load i18n %}

{% comment %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form id="voting_form_{{ survey.pk }}" method="POST" action="{% url 'survey:process_vote' slug=survey.slug %}">
{% csrf_token %}
{% for question in survey.questions %}

  <div>
    {{ question.question_text }}
    <ul>
    {% for choice in question.choices %}
      <li>
        <input type="radio"
            name="choice[{{ question.pk }}]"
            id="choice_{{ question.pk }}_{{ forloop.counter }}"
            value="{{ choice.pk }}" />
        <label for="choice_{{ question.pk }}_{{ forloop.counter }}">
          {{ choice.choice_text }}
        </label>
      </li>
    {% endfor %}
    </ul>
  </div>
{% endfor %}

</form>

{% endcomment %}


<form method="POST" action="{% url 'survey:form' slug=survey.slug %}">
  {% csrf_token %}

  {% for field in response_form %}
    {% if 'question_' in field.name %}
      {% if field.field.required %}
      <div class="field-wrapper question-required">
        {{ field.errors }}
        <span class="asterix"> * </span><label class="label-inline">{{ field.label }}</label>
      {% else %}
      <div class="field-wrapper">
        {{ field.errors }}
        <label class="label-inline">{{ field.label }}</label>
      {% endif %}
        <span class="form-help-text">{{ field.help_text}}</span>
        <div class="form-field-body">
            {{ field }}
        </div>
      </div>
    {% endif %}
  {% endfor %}

  <div class="field-wrapper">
    {{ response_form.comments.errors }}
    {{ response_form.comments.label_tag }}
    <span class="form-help-text">{{ response_form.comments.help_text}}</span>
    <div class="form-field-body">
      {{ response_form.comments }}
    </div>
  </div>

  <div class="submit-button"><input type="submit" value="Submit !"></div>

</form>
{% endblock %}

multilingual_survey/templates/multilingual_survey/success.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
<div class="row">

<div class="jumbotron">
  <h1>Thank you {{request.user.username}} for your response !</h1>
  <p>Your response has been forwarded to our server !</p>
</div>
</div>
</div>
{% endblock %}

multilingual_survey/templates/multilingual_survey/survey.html
{% extends 'base.html' %}
{% load url from future %}
{% load i18n %}
{% block content %}
<form method="POST" action="">
  {% csrf_token %}

  <ul>
  {% for question in survey.question_set.all %}
    <li>
      <span>{{ question.question_text }}</span>
      <ul>
      {% for choice in question.choice_set.all %}
        <li>{{ choice }}</li>
      {% endfor %}
      </ul>
    </li>
  {% endfor %}
  </ul>

  {% for field in response_form %}
    {% if 'question_' in field.name %}
      {% if field.field.required %}
      <div class="field-wrapper question-required">
        {{ field.errors }}
        <span class="asterix"> * </span><label class="label-inline">{{ field.label }}</label>
      {% else %}
      <div class="field-wrapper">
        {{ field.errors }}
        <label class="label-inline">{{ field.label }}</label>
      {% endif %}
        <span class="form-help-text">{{ field.help_text}}</span>
        <div class="form-field-body">
            {{ field }}
        </div>
      </div>
    {% endif %}
  {% endfor %}

  <div class="field-wrapper">
    {{ response_form.comments.errors }}
    {{ response_form.comments.label_tag }}
    <span class="form-help-text">{{ response_form.comments.help_text}}</span>
    <div class="form-field-body">
      {{ response_form.comments }}
    </div>
  </div>

  <div class="submit-button"><input type="submit" value="Submit"></div>

</form>
{% endblock %}